[package]
name = "libmussh"
version = "0.1.0"
authors = ["Jason Ozias <jason.ozias@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2"
getset = "0"
indexmap = "1"
serde = "1"
serde_derive = "1"
toml = "0"
wait_group = "0"

[dependencies.lazy_static]
version = "1"
features = ["nightly"]